version: '3.8'

services:
  db:

    image: postgres:13
    container_name: immobilier_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:    
      POSTGRES_DB: immobilier_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    environment:
      DATABASE_URL: 'postgresql://postgres:   @db:5432/immobilier_db'
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  db_data:
